import React from 'react';

const API_BASE=(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'');
export default function LearningCenter(){
 const [data,setData]=React.useState<any>(null); const [prefs,setPrefs]=React.useState<any[]>([]); const [loading,setLoading]=React.useState(true);
 const load=React.useCallback(async()=>{setLoading(true);try{const [a,b]=await Promise.all([fetch(`${API_BASE}/api/v1/learning/overview`),fetch(`${API_BASE}/api/v1/learning/preferences`)]);setData(await a.json());setPrefs(await b.json())}finally{setLoading(false)}},[]);
 React.useEffect(()=>{load()},[load]);
 const status=async(id:number,s:string)=>{await fetch(`${API_BASE}/api/v1/learning/preferences/${id}/status?status=${encodeURIComponent(s)}`,{method:'POST'});load()};
 return <section className="module-page"><div className="module-hero ai"><div className="module-mark">🧠</div><div><p className="eyebrow">INTELLIGENCE · SELF LEARNING</p><h2>AI Learning Center</h2><p>Seller feedback, corrections and outcomes improve future recommendations without bypassing safety controls.</p></div><span className="connection">● {loading?'Learning':'Live'}</span></div>
 <div className="cards"><Metric t="Feedback Events" v={data?.events??'—'}/><Metric t="Confirmed Preferences" v={data?.confirmed_preferences??'—'}/><Metric t="Candidate Patterns" v={data?.candidate_preferences??'—'}/><Metric t="Outcomes" v={data?.outcomes??'—'}/><Metric t="Success Rate" v={data?.success_rate==null?'—':`${Math.round(data.success_rate*100)}%`}/></div>
 <div className="grid module-grid"><article className="panel"><Head t="Learned Preferences" s="Seller-scoped patterns with evidence"/>{prefs.length?<div className="rows">{prefs.map(p=><div key={p.id}><b>{p.key}</b><strong>{p.status}</strong><em>Confidence {Math.round(p.confidence*100)}% · Evidence {p.evidence_count}</em><span>{p.value}</span><button onClick={()=>status(p.id,p.status==='confirmed'?'disabled':'confirmed')}>{p.status==='confirmed'?'Disable':'Confirm'}</button></div>)}</div>:<Empty/>}</article><article className="panel"><Head t="Learning Safety" s="Learning influences decisions but cannot bypass policy"/><div className="rows"><div><b>Seller isolation</b><strong>ENFORCED</strong><em>Every event is seller scoped</em></div><div><b>High-risk actions</b><strong>BLOCKED</strong><em>Existing safety gates remain authoritative</em></div><div><b>Confidence</b><strong>CALIBRATED</strong><em>Historical feedback adjusts raw confidence</em></div><div><b>Contradictions</b><strong>REVIEW</strong><em>Conflicting patterns remain candidates</em></div></div></article></div></section>;
}
function Metric({t,v}:{t:string;v:React.ReactNode}){return <article className="card"><span>{t}</span><strong>{v}</strong><small>Live learning signal</small></article>}; function Head({t,s}:{t:string;s:string}){return <div className="panelhead"><div><h2>{t}</h2><p>{s}</p></div></div>}; function Empty(){return <div className="empty"><strong>No learning patterns yet</strong><small>Approved, edited or corrected AI suggestions will appear here.</small></div>}
