import React from 'react';

const API_BASE = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');
const api = (path: string, init?: RequestInit) => fetch(`${API_BASE}/api/v1${path}`, { ...init, headers: { Accept: 'application/json', ...(init?.headers || {}) } });

type Diagnostic = { id:number; code:string; category:string; severity:string; status:string; title:string; message:string; root_cause:string; impact:Record<string,unknown>; proposed_fix:Record<string,unknown>; confidence:number; fix_risk:string; auto_fixable:boolean };

export default function DiagnosticWorkspace() {
  const [items,setItems]=React.useState<Diagnostic[]>([]); const [summary,setSummary]=React.useState<Record<string,number>>({}); const [busy,setBusy]=React.useState(false); const [message,setMessage]=React.useState('');
  const refresh=React.useCallback(async()=>{ const [a,b]=await Promise.all([api('/diagnostics'),api('/diagnostics/summary')]); if(a.ok)setItems(await a.json()); if(b.ok)setSummary(await b.json()); },[]);
  React.useEffect(()=>{refresh();},[refresh]);
  const scan=async()=>{setBusy(true);setMessage('Scanning catalog and listings…'); try{const r=await api('/diagnostics/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})}); if(!r.ok)throw new Error(`Scan failed (${r.status})`); await refresh();setMessage('Diagnostic scan complete.');}catch(e){setMessage(e instanceof Error?e.message:'Scan failed');}finally{setBusy(false);}};
  const fix=async(id:number)=>{setBusy(true);setMessage('Preparing a safe fix…');try{const p=await api(`/diagnostics/${id}/fix-preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'dry_run'})});if(!p.ok)throw new Error((await p.json()).detail||'Preview failed');const r=await api(`/diagnostics/${id}/fix`,{method:'POST'});if(!r.ok)throw new Error((await r.json()).detail||'Fix failed');await refresh();setMessage('Fix applied and verification completed.');}catch(e){setMessage(e instanceof Error?e.message:'Fix failed');}finally{setBusy(false);}};
  return <section className="module-page"><div className="module-hero ai"><div className="module-mark">⌁</div><div><p className="eyebrow">INTELLIGENCE CENTER</p><h2>AI Diagnostics</h2><p>Root cause analysis, safe fix planning and post-fix verification.</p></div><span className="connection">● {busy?'Working':'Ready'}</span></div><div className="cards">{[['Critical',summary.critical||0],['High',summary.high||0],['Medium',summary.medium||0],['Low',summary.low||0],['Total',summary.total||0]].map(([a,b])=><article className="card" key={String(a)}><span>{a}</span><strong>{String(b)}</strong><small>Open diagnostics</small></article>)}</div><div className="module-data"><article className="panel"><div className="panelhead"><div><h2>Diagnostic engine</h2><p>Detect → diagnose → safely fix → verify</p></div><button onClick={scan} disabled={busy}>↻ {busy?'Working':'Scan now'}</button></div>{message&&<div className="empty"><strong>{message}</strong></div>}{items.length?<div className="rows">{items.map(d=><div key={d.id}><b>{d.title}</b><strong>{d.severity.toUpperCase()} · {d.confidence}%</strong><em>{d.root_cause} {d.auto_fixable?<button onClick={()=>fix(d.id)} disabled={busy}>Safe fix →</button>:''}</em></div>)}</div>:<div className="empty"><strong>No open diagnostics</strong><small>Run a scan to analyze the current catalog and listings.</small></div>}</article></div></section>;
}
