import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type KPI={label:string,value:string,delta:string};
const kpis:KPI[]=[{label:'Revenue',value:'₹0',delta:'Selected period'},{label:'Net Profit',value:'₹0',delta:'Finance synced'},{label:'Orders',value:'0',delta:'Amazon + Flipkart'},{label:'Inventory',value:'0',delta:'Available units'},{label:'Buy Box',value:'0%',delta:'No snapshots yet'},{label:'Returns',value:'0',delta:'Selected period'}];
const nav=['Dashboard','Orders','Products','Listings','Inventory','Pricing','Returns','Customers','Finance','Advertising','Analytics','AI Agents','Automations','Notifications','Settings'];
function App(){const [active,setActive]=React.useState('Dashboard');return <div className="shell"><aside><div className="brand"><span>◆</span><div><b>Seller Hub</b><small>AI Operations</small></div></div><nav>{nav.map(n=><button className={active===n?'active':''} onClick={()=>setActive(n)} key={n}>{n}</button>)}</nav><div className="seller"><small>SELLER ACCOUNT</small><strong>My Business</strong><span>● Connected</span></div></aside><main><header><div><p className="eyebrow">COMMAND CENTER</p><h1>{active}</h1><p className="muted">Amazon + Flipkart operations at a glance.</p></div><div className="actions"><button>↻ Sync</button><button className="primary">+ Quick Action</button></div></header>{active==='Dashboard'?<Dashboard/>:<section className="placeholder"><div className="icon">◇</div><h2>{active}</h2><p>This workspace is ready for the next module integration.</p></section>}</main></div>}
function Dashboard(){return <><section className="cards">{kpis.map(k=><article className="card" key={k.label}><span>{k.label}</span><strong>{k.value}</strong><small>{k.delta}</small></article>)}</section><section className="grid"><article className="panel chart"><div className="panelhead"><div><h2>Sales & Profit</h2><p>Last 30 days</p></div><select><option>30 days</option><option>90 days</option><option>1 year</option></select></div><div className="emptychart"><div className="line"></div><span>No sales data yet</span><small>Connect marketplace accounts and sync orders to populate trends.</small></div></article><article className="panel"><div className="panelhead"><div><h2>Alerts</h2><p>Needs attention</p></div></div><div className="alert"><b>✓</b><div><strong>All systems clear</strong><span>No critical alerts right now.</span></div></div></article></section><section className="grid bottom"><article className="panel"><div className="panelhead"><div><h2>Marketplace</h2><p>Performance comparison</p></div></div><div className="rows"><div><span>Amazon</span><b>₹0</b><em>0 orders</em></div><div><span>Flipkart</span><b>₹0</b><em>0 orders</em></div></div></article><article className="panel"><div className="panelhead"><div><h2>Top Products</h2><p>By revenue</p></div></div><div className="empty"><span>No product sales yet</span></div></article></section></>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);