import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type KPI = { label: string; value: string; delta: string };
type Dashboard = { kpis: { revenue: number; net_profit: number; orders: number; inventory_units: number; buy_box_rate: number; returns: number }; trends: { key: string; revenue: number; net_profit: number }[]; marketplaces: { marketplace: string; revenue: number; orders: number; net_profit: number }[]; alerts: { type: string; severity: string; message: string; count: number }[]; top_products: { sku: string; title: string; revenue: number; units: number }[] };
type Command = { id: number; query: string; intent: string; status: string; trace_id: string; answer: string; evidence: string[]; recommendations: string[]; actions: { agent: string; task: string; reason: string; requires_approval: boolean; status: string; output: Record<string, unknown> }[]; created_at: string };

const nav = ['Dashboard', 'Orders', 'Products', 'Listings', 'Inventory', 'Pricing', 'Returns', 'Customers', 'Finance', 'Advertising', 'Analytics', 'AI Agents', 'Automations', 'Notifications', 'Settings'];
const emptyDashboard: Dashboard = { kpis: { revenue: 0, net_profit: 0, orders: 0, inventory_units: 0, buy_box_rate: 0, returns: 0 }, trends: [], marketplaces: [], alerts: [], top_products: [] };

function api(path: string, init?: RequestInit) {
  const token = sessionStorage.getItem('seller_hub_token');
  return fetch(`/api/v1${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(init?.headers || {}) } });
}

function App() {
  const [active, setActive] = React.useState('Dashboard');
  const [dark, setDark] = React.useState(() => localStorage.getItem('seller_hub_theme') === 'dark');
  React.useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('seller_hub_theme', dark ? 'dark' : 'light'); }, [dark]);
  return <div className="shell"><a className="skip-link" href="#main-content">Skip to main content</a><aside aria-label="Seller Hub navigation"><div className="brand"><span aria-hidden="true">◆</span><div><b>Seller Hub</b><small>AI Operations</small></div></div><nav aria-label="Primary navigation">{nav.map(n => <button aria-current={active === n ? 'page' : undefined} className={active === n ? 'active' : ''} onClick={() => setActive(n)} key={n} title={n}>{n}</button>)}</nav><div className="seller"><small>SELLER ACCOUNT</small><strong>My Business</strong><span>● Connected</span></div></aside><main id="main-content" tabIndex={-1}><header><div><p className="eyebrow">{active === 'AI Agents' ? 'AI COMMAND CENTER' : 'COMMAND CENTER'}</p><h1>{active}</h1><p className="muted">Amazon + Flipkart operations at a glance.</p></div><div className="actions"><button aria-label="Toggle dark mode" onClick={() => setDark(!dark)}>{dark ? '☀ Light' : '◐ Dark'}</button><button onClick={() => setActive('AI Agents')} className="primary">✦ Ask AI</button></div></header>{active === 'Dashboard' ? <Dashboard /> : active === 'AI Agents' ? <AICommandCenter /> : active === 'Settings' ? <Settings /> : <section className="placeholder" aria-live="polite"><div className="icon" aria-hidden="true">◇</div><h2>{active}</h2><p>This workspace is ready for the next module integration.</p></section>}</main></div>;
}

function Dashboard() {
  const [data, setData] = React.useState<Dashboard>(emptyDashboard); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState('');
  const load = React.useCallback(async () => { setLoading(true); setError(''); try { const response = await api('/dashboard'); if (!response.ok) throw new Error(response.status === 401 ? 'Connect your Seller Hub account in Settings.' : `Dashboard request failed (${response.status}).`); setData(await response.json()); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load dashboard.'); } finally { setLoading(false); } }, []);
  React.useEffect(() => { load(); }, [load]);
  const k = data.kpis; const kpis: KPI[] = [{ label: 'Revenue', value: `₹${k.revenue.toLocaleString('en-IN')}`, delta: 'Last 30 days' }, { label: 'Net Profit', value: `₹${k.net_profit.toLocaleString('en-IN')}`, delta: 'After tracked expenses' }, { label: 'Orders', value: `${k.orders}`, delta: 'Amazon + Flipkart' }, { label: 'Inventory', value: `${k.inventory_units}`, delta: 'Available units' }, { label: 'Buy Box', value: `${k.buy_box_rate}%`, delta: 'Captured snapshots' }, { label: 'Returns', value: `${k.returns}`, delta: 'Selected period' }];
  return <>{error ? <div className="errorbar" role="alert">{error}</div> : null}<section className="cards" aria-label="Key performance indicators">{kpis.map(x => <article className="card" key={x.label}><span>{x.label}</span><strong>{loading ? '—' : x.value}</strong><small>{x.delta}</small></article>)}</section><section className="grid"><article className="panel chart"><div className="panelhead"><div><h2>Sales &amp; Profit</h2><p>Last 30 days</p></div><button onClick={load} aria-label="Refresh sales and profit">↻ Refresh</button></div>{data.trends.length ? <div className="trendlist">{data.trends.slice(-10).map(t => <div key={t.key}><span>{t.key}</span><b>₹{t.revenue.toLocaleString('en-IN')}</b><em>₹{t.net_profit.toLocaleString('en-IN')} profit</em></div>)}</div> : <Empty text={loading ? 'Loading live data…' : 'No sales data yet'} sub="Connect marketplace accounts and sync orders to populate trends." />}</article><article className="panel"><div className="panelhead"><div><h2>Alerts</h2><p>Needs attention</p></div></div>{data.alerts.length ? data.alerts.map(a => <div className="alert" key={`${a.type}-${a.message}`}><b aria-hidden="true">!</b><div><strong>{a.message}</strong><span>{a.count} item(s) · {a.severity}</span></div></div>) : <Empty text={loading ? 'Loading…' : 'All systems clear'} sub="No critical alerts right now." />}</article></section><section className="grid bottom"><article className="panel"><div className="panelhead"><div><h2>Marketplace</h2><p>Performance comparison</p></div></div>{data.marketplaces.length ? <div className="rows">{data.marketplaces.map(m => <div key={m.marketplace}><span>{m.marketplace}</span><b>₹{m.revenue.toLocaleString('en-IN')}</b><em>{m.orders} orders · ₹{m.net_profit.toLocaleString('en-IN')} profit</em></div>)}</div> : <Empty text={loading ? 'Loading…' : 'No marketplace data'} />}</article><article className="panel"><div className="panelhead"><div><h2>Top Products</h2><p>By revenue</p></div></div>{data.top_products.length ? <div className="rows">{data.top_products.slice(0, 5).map(p => <div key={p.sku}><span>{p.sku}</span><b>₹{p.revenue.toLocaleString('en-IN')}</b><em>{p.units} units · {p.title}</em></div>)}</div> : <Empty text={loading ? 'Loading…' : 'No product sales yet'} />}</article></section></>;
}

function AICommandCenter() {
  const [query, setQuery] = React.useState('आज Amazon पर sales कम क्यों हुई?'); const [sellerId, setSellerId] = React.useState(() => sessionStorage.getItem('seller_hub_seller_id') || ''); const [result, setResult] = React.useState<Command | null>(null); const [history, setHistory] = React.useState<Command[]>([]); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState('');
  const run = async (execute = false) => { if (!sellerId) { setError('Set your Seller Account ID in Settings first.'); return; } setLoading(true); setError(''); try { const response = await api(`/ai/commands?seller_account_id=${encodeURIComponent(sellerId)}`, { method: 'POST', body: JSON.stringify({ query, execute_actions: execute, approved: execute }) }); if (!response.ok) throw new Error((await response.json()).detail || `Command failed (${response.status}).`); const body = await response.json(); setResult(body); setHistory(prev => [body, ...prev.filter(x => x.id !== body.id)]); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to run AI command.'); } finally { setLoading(false); } };
  const loadHistory = React.useCallback(async () => { if (!sellerId) return; const response = await api(`/ai/commands/history?seller_account_id=${encodeURIComponent(sellerId)}`); if (response.ok) setHistory((await response.json()).commands); }, [sellerId]); React.useEffect(() => { loadHistory(); }, [loadHistory]);
  return <section className="ai-layout"><article className="panel ai-hero"><p className="eyebrow">NATURAL LANGUAGE OPERATIONS</p><h2>Ask your Seller Hub anything</h2><p>AI compares the latest 30 days with the previous 30 days, explains the signal, proposes specialist agents, and requires approval before operational actions.</p><div className="commandbox"><textarea aria-label="AI command" value={query} onChange={e => setQuery(e.target.value)} rows={3} placeholder="e.g. आज Amazon पर sales कम क्यों हुई?" /><button className="primary" disabled={loading} onClick={() => run(false)}>{loading ? 'Analyzing…' : 'Analyze'}</button></div>{error && <div className="errorbar" role="alert">{error}</div>}<div className="suggestions" aria-label="Suggested commands"><button onClick={() => setQuery('आज Amazon पर sales कम क्यों हुई?')}>Sales decline</button><button onClick={() => setQuery('Which products are low on stock?')}>Inventory</button><button onClick={() => setQuery('Should I change pricing?')}>Pricing</button><button onClick={() => setQuery('How is advertising performing?')}>Ads</button></div></article>{result && <article className="panel" aria-live="polite"><div className="panelhead"><div><h2>AI Analysis</h2><p>{result.intent} · trace {result.trace_id.slice(0, 8)}</p></div><span className={`status ${result.status}`}>{result.status}</span></div><p className="answer">{result.answer}</p><h3>Evidence</h3><ul>{result.evidence.map(x => <li key={x}>{x}</li>)}</ul><h3>Recommendations</h3><ul>{result.recommendations.map(x => <li key={x}>{x}</li>)}</ul><h3>Proposed actions</h3>{result.actions.map(a => <div className="actionrow" key={`${a.agent}-${a.task}`}><div><strong>{a.agent}</strong><span>{a.task} · {a.reason}</span></div><em>{a.requires_approval ? 'Approval required' : 'Analysis only'}</em></div>)}{result.actions.some(a => a.requires_approval && a.status === 'proposed') && <button className="primary execute" onClick={() => run(true)} disabled={loading}>✓ Approve &amp; Execute proposed actions</button>}</article>}<article className="panel"><div className="panelhead"><div><h2>Command history</h2><p>Seller-scoped audit trail</p></div><button onClick={loadHistory}>↻ Refresh</button></div>{history.length ? history.slice(0, 10).map(item => <button className="historyrow" onClick={() => setResult(item)} key={item.id}><strong>{item.query}</strong><span>{item.intent} · {item.status} · {new Date(item.created_at).toLocaleString()}</span></button>) : <Empty text="No command history yet" sub="Run an AI command to create an explainable audit record." />}</article></section>;
}

function Settings() { const [token, setToken] = React.useState(() => sessionStorage.getItem('seller_hub_token') || ''); const [sellerId, setSellerId] = React.useState(() => sessionStorage.getItem('seller_hub_seller_id') || ''); const [saved, setSaved] = React.useState(false); const save = () => { sessionStorage.setItem('seller_hub_token', token.trim()); sessionStorage.setItem('seller_hub_seller_id', sellerId.trim()); setSaved(true); }; return <section className="panel settings"><h2>Connection settings</h2><p>Use the API token from Seller Hub login and your seller account ID for AI command execution.</p><label>Bearer token<input type="password" autoComplete="off" value={token} onChange={e => { setToken(e.target.value); setSaved(false); }} placeholder="Paste access token" /></label><label>Seller account ID<input inputMode="numeric" value={sellerId} onChange={e => { setSellerId(e.target.value); setSaved(false); }} placeholder="e.g. 1" /></label><button className="primary" onClick={save}>Save for this session</button>{saved && <p className="save-status" role="status">Saved for this browser session.</p>}</section>; }
function Empty({ text, sub = '' }: { text: string; sub?: string }) { return <div className="empty"><span>{text}</span>{sub && <small>{sub}</small>}</div>; }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
