import './operations-center.css';
import React from 'react';

const API_BASE = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');
const api = (path: string, options?: RequestInit) => fetch(`${API_BASE}/api/v1${path}`, { ...options, headers: { Accept: 'application/json', 'Content-Type': 'application/json', ...(options?.headers || {}) } });

type Data = { health: { overall: number; components: Record<string, number>; reasons: { area: string; impact: number; message: string }[] }; kpis: { orders: number; products: number; listings: number; inventory_units: number; low_stock: number; out_of_stock: number; returns: number; pending_jobs: number; pending_approvals: number }; orders: { by_status: Record<string, number> }; inventory: { total_items: number; units: number; low_stock: number; out_of_stock: number }; catalog: { products: number; listings: number; active_listings: number }; diagnostics: Record<string, number>; listing_validation: Record<string, number>; marketplaces: { id: number; marketplace: string; status: string; last_sync_at: string | null; last_error: string | null }[]; alerts: { id: number; severity: string; title: string; message: string; source: string; is_read: boolean }[]; action_queue: { id: number; action: string; risk: string; status: string; reason: string | null; created_at: string | null }[] };

export default function OperationsControlCenter() {
  const [data, setData] = React.useState<Data | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState('');
  const [updated, setUpdated] = React.useState<Date | null>(null);
  const load = React.useCallback(async () => { setLoading(true); try { const response = await api('/seller-operations/overview?refresh=true'); if (!response.ok) throw new Error(`Operations API returned ${response.status}`); setData(await response.json()); setUpdated(new Date()); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load operations center'); } finally { setLoading(false); } }, []);
  React.useEffect(() => { load(); const timer = window.setInterval(load, 30000); return () => window.clearInterval(timer); }, [load]);
  const markRead = async (id: number) => { const response = await api(`/seller-operations/alerts/${id}/read`, { method: 'POST' }); if (response.ok) await load(); };
  const h = data?.health; const k = data?.kpis; const pending = data?.action_queue.filter(a => a.status === 'pending').length || 0;
  return <section className="module-page operations-center">
    <div className="module-hero ai"><div className="module-mark">⚡</div><div><p className="eyebrow">OPERATIONS · COMMAND CENTER</p><h2>Seller Operations</h2><p>One operational view for listings, inventory, orders, marketplaces, diagnostics and controlled AI actions.</p></div><span className="connection">● {loading ? 'Refreshing' : 'Live'}</span></div>
    {error && <div className="errorbar" role="alert">{error}<button onClick={load}>Retry</button></div>}
    <div className="cards"><Metric title="Business Health" value={h?.overall ?? '—'} sub="Explainable 0–100 score"/><Metric title="Listings" value={k?.listings ?? '—'} sub={`${data?.catalog.active_listings ?? 0} active`}/><Metric title="Inventory" value={k?.inventory_units ?? '—'} sub={`${k?.low_stock ?? 0} low · ${k?.out_of_stock ?? 0} OOS`}/><Metric title="Orders" value={k?.orders ?? '—'} sub={`${k?.pending_jobs ?? 0} pending jobs`}/><Metric title="AI Actions" value={pending} sub="Awaiting approval"/></div>
    <div className="grid module-grid"><article className="panel health-panel"><PanelHead title="Business Health" sub={updated ? `Updated ${updated.toLocaleTimeString('en-IN')}` : 'Calculating operational health'}/><div className="health-score"><strong>{h?.overall ?? '—'}</strong><span>/100</span></div><div className="health-bars">{Object.entries(h?.components || {}).map(([name, score]) => <div className="health-row" key={name}><span>{name.replaceAll('_',' ')}</span><b>{score}</b><i><em style={{ width: `${score}%` }}/></i></div>)}</div></article><article className="panel"><PanelHead title="Why this score?" sub="The biggest operational factors"/>{h?.reasons.length ? <div className="rows">{h.reasons.map((reason, i) => <div key={`${reason.area}-${i}`}><b>{reason.message}</b><strong>{reason.impact}</strong><em>{reason.area}</em></div>)}</div> : <Empty text="No health penalties detected" sub="Your operational signals are clean."/>}</article></div>
    <div className="grid module-grid"><article className="panel"><PanelHead title="AI Action Queue" sub="Risk-aware actions from the existing Seller Hub control layer"/>{data?.action_queue.length ? <div className="rows">{data.action_queue.slice(0,10).map(a => <div key={a.id}><b>#{a.id} · {a.action}</b><strong>{a.status}</strong><em>{a.risk} risk · {a.reason || 'No reason supplied'}</em></div>)}</div> : <Empty text="Action queue is clear" sub="No controlled AI action is waiting."/>}</article><article className="panel"><PanelHead title="Critical Alerts" sub="Seller-scoped operational signals"/>{data?.alerts.length ? <div className="rows">{data.alerts.slice(0,8).map(a => <div key={a.id}><b>{a.title}</b><strong>{a.severity}</strong><em>{a.message} · {a.source}</em><button onClick={() => markRead(a.id)}>Mark read</button></div>)}</div> : <Empty text="No active alerts" sub="Nothing requires immediate attention."/>}</article></div>
    <div className="grid module-grid"><article className="panel"><PanelHead title="Marketplace Health" sub="Connection and latest synchronization state"/>{data?.marketplaces.length ? <div className="rows">{data.marketplaces.map(m => <div key={m.id}><b>{m.marketplace}</b><strong>{m.status}</strong><em>Last sync: {m.last_sync_at ? new Date(m.last_sync_at).toLocaleString('en-IN') : '—'}{m.last_error ? ` · ${m.last_error}` : ''}</em></div>)}</div> : <Empty text="No marketplace accounts" sub="Connect Amazon or Flipkart to activate marketplace signals."/>}</article><article className="panel"><PanelHead title="Listing & Vision Health" sub="Phase 67–69 quality signals"/><div className="rows"><div><b>Active listings</b><strong>{data?.catalog.active_listings ?? 0}</strong><em>of {data?.catalog.listings ?? 0}</em></div>{Object.entries(data?.listing_validation || {}).map(([status,count]) => <div key={status}><b>Validation · {status}</b><strong>{count}</strong><em>listing records</em></div>)}{Object.entries(data?.diagnostics || {}).map(([severity,count]) => <div key={severity}><b>Diagnostics · {severity}</b><strong>{count}</strong><em>open findings</em></div>)}</div></article></div>
    <div className="grid module-grid"><article className="panel"><PanelHead title="Operations Snapshot" sub="Live business counters"/><div className="rows"><div><b>Products</b><strong>{k?.products ?? 0}</strong><em>catalog</em></div><div><b>Returns</b><strong>{k?.returns ?? 0}</strong><em>requests</em></div><div><b>Tracked inventory</b><strong>{data?.inventory.total_items ?? 0}</strong><em>SKUs</em></div><div><b>Order status groups</b><strong>{Object.keys(data?.orders.by_status || {}).length}</strong><em>active groups</em></div></div></article><article className="panel"><PanelHead title="Safety Gate" sub="Autonomy boundaries"/><Check text="Seller ownership is enforced on operations data"/><Check text="Low-risk actions remain controlled by existing action policies"/><Check text="Medium/high-risk changes require approval"/><Check text="Credentials remain server-side"/><Check text="Health snapshots and alerts are auditable"/></article></div>
    <div className="operations-footer"><span>● Live operational aggregation</span><button onClick={load}>↻ Refresh</button></div>
  </section>;
}
function Metric({ title, value, sub }: { title: string; value: React.ReactNode; sub: string }) { return <article className="card"><span>{title}</span><strong>{value}</strong><small>{sub}</small></article>; }
function PanelHead({ title, sub }: { title: string; sub: string }) { return <div className="panelhead"><div><h2>{title}</h2><p>{sub}</p></div></div>; }
function Check({ text }: { text: string }) { return <div className="check"><b>✓</b><span>{text}</span></div>; }
function Empty({ text, sub }: { text: string; sub?: string }) { return <div className="empty"><strong>{text}</strong>{sub && <small>{sub}</small>}</div>; }
