export type SellerHubCapability = {
  id: string;
  label: string;
  group: 'SELL' | 'GROW' | 'AUTOMATE' | 'SYSTEM';
  icon: string;
  description: string;
  capabilities: string[];
  ai: boolean;
};

/**
 * Seller Hub is the canonical product contract for the UI. Individual workspaces
 * consume this registry to keep navigation, labels and acceptance scope in sync.
 */
export const sellerHubCapabilities: SellerHubCapability[] = [
  { id: 'orders', label: 'Orders', group: 'SELL', icon: '▣', description: 'Unified order lifecycle and SLA operations', ai: true, capabilities: ['new', 'confirmed', 'processing', 'packed', 'shipped', 'delivered', 'cancelled', 'returns', 'refunds', 'SLA breach', 'search/filter', 'order detail', 'invoice', 'shipping label', 'tracking', 'bulk actions', 'export'] },
  { id: 'products', label: 'Products', group: 'SELL', icon: '◫', description: 'Master product catalog and enrichment', ai: true, capabilities: ['SKU', 'product ID', 'HSN', 'GST', 'brand', 'category', 'attributes', 'variants', 'media', 'description', 'bullets', 'keywords', 'dimensions', 'weight', 'manufacturer', 'country of origin', 'compliance', 'duplicate detection', 'bulk import/export'] },
  { id: 'listings', label: 'Listings', group: 'SELL', icon: '▤', description: 'Marketplace listing lifecycle and quality', ai: true, capabilities: ['active', 'inactive', 'draft', 'suppressed', 'blocked', 'failed', 'quality score', 'SEO score', 'marketplace mapping', 'SKU mapping', 'sync', 'bulk update', 'history'] },
  { id: 'inventory', label: 'Inventory', group: 'SELL', icon: '▥', description: 'Stock health, planning and replenishment', ai: true, capabilities: ['available', 'reserved', 'damaged', 'in-transit', 'low stock', 'out of stock', 'SKU view', 'marketplace view', 'warehouse view', 'stock movement', 'adjustment', 'transfer', 'history', 'reorder level', 'safety stock', 'days of inventory', 'dead stock', 'slow/fast moving', 'overstock', 'stockout prediction', 'purchase planning'] },
  { id: 'returns', label: 'Returns', group: 'SELL', icon: '↩', description: 'Returns, refunds and customer issues', ai: true, capabilities: ['requests', 'approval/rejection', 'pickup', 'transit', 'received', 'refund pending', 'refunded', 'return reasons', 'return rate', 'refund amount', 'return cost', 'customer issues', 'abuse signals'] },
  { id: 'pricing', label: 'Pricing', group: 'GROW', icon: '₹', description: 'Pricing intelligence and margin protection', ai: true, capabilities: ['cost', 'selling price', 'MRP', 'discount', 'min/max', 'competitor price', 'Buy Box', 'history', 'rules', 'scheduled pricing', 'bulk update', 'dynamic pricing', 'margin protection', 'simulation'] },
  { id: 'advertising', label: 'Advertising', group: 'GROW', icon: '◒', description: 'Campaign performance and optimization', ai: true, capabilities: ['campaigns', 'ad groups', 'keywords', 'search terms', 'impressions', 'clicks', 'CTR', 'CPC', 'spend', 'sales', 'ACOS', 'ROAS', 'conversion', 'budgets', 'alerts', 'bulk actions', 'wasted spend'] },
  { id: 'analytics', label: 'Analytics', group: 'GROW', icon: '⌁', description: 'Business intelligence and forecasting', ai: true, capabilities: ['sales', 'orders', 'product/SKU', 'listing', 'inventory', 'pricing', 'advertising', 'returns', 'profit', 'marketplace comparison', 'customer', 'growth', 'trends', 'forecasting', 'cohorts', 'top/worst performers', 'custom reports', 'export'] },
  { id: 'finance', label: 'Finance', group: 'GROW', icon: '◈', description: 'Revenue, fees, settlements and profitability', ai: true, capabilities: ['revenue', 'GMV', 'net sales', 'marketplace fees', 'commission', 'shipping', 'referral fees', 'advertising cost', 'return cost', 'refunds', 'GST', 'TCS', 'TDS', 'COGS', 'gross profit', 'net profit', 'margin', 'settlement', 'reconciliation', 'payouts', 'SKU profitability'] },
  { id: 'automations', label: 'Automations', group: 'AUTOMATE', icon: '⚙', description: 'Scheduled and event-driven seller workflows', ai: true, capabilities: ['triggers', 'conditions', 'actions', 'scheduled jobs', 'recurring jobs', 'inventory', 'pricing', 'listing', 'order', 'advertising', 'notification', 'AI automations', 'logs', 'retry', 'pause/resume', 'history'] },
  { id: 'ai-listing-studio', label: 'AI Listing Studio', group: 'AUTOMATE', icon: '✦', description: 'Generate, validate and adapt marketplace listings', ai: true, capabilities: ['product input', 'image analysis', 'title', 'bullets', 'description', 'keywords', 'attributes', 'SEO', 'compliance', 'Amazon variant', 'Flipkart variant', 'quality score', 'regenerate', 'compare', 'save draft', 'publish'] },
  { id: 'ai-seller-copilot', label: 'AI Seller Copilot', group: 'AUTOMATE', icon: '✦', description: 'Natural-language seller operations and action planning', ai: true, capabilities: ['business questions', 'daily briefing', 'critical alerts', 'opportunity detection', 'anomaly detection', 'root cause analysis', 'recommendations', 'execute action', 'approval', 'action history'] },
  { id: 'marketplaces', label: 'Marketplaces', group: 'SYSTEM', icon: '◇', description: 'Amazon and Flipkart accounts, mapping and sync', ai: true, capabilities: ['Amazon', 'Flipkart', 'connect account', 'authentication', 'API status', 'last sync', 'sync now', 'sync history', 'API errors', 'category mapping', 'attribute mapping', 'SKU mapping', 'health', 'recovery'] },
  { id: 'notifications', label: 'Notifications', group: 'SYSTEM', icon: '♢', description: 'Operational alerts and preferences', ai: true, capabilities: ['critical', 'warning', 'info', 'order alerts', 'inventory alerts', 'listing alerts', 'pricing alerts', 'advertising alerts', 'finance alerts', 'marketplace alerts', 'AI alerts', 'read/unread', 'preferences'] },
  { id: 'control-center', label: 'Control Center', group: 'SYSTEM', icon: '⚡', description: 'Execution, approvals, recovery and audit trail', ai: true, capabilities: ['running', 'queued', 'completed', 'failed', 'approvals', 'AI actions', 'system actions', 'execution history', 'rollback', 'recovery', 'audit trail', 'job details'] },
  { id: 'diagnostics', label: 'Diagnostics', group: 'SYSTEM', icon: '⌁', description: 'System, marketplace and workflow health', ai: true, capabilities: ['system health', 'marketplace health', 'API health', 'sync health', 'listing errors', 'order errors', 'inventory errors', 'automation errors', 'AI errors', 'root cause', 'error logs', 'suggested fix', 'one-click fix', 'retry', 'recovery history'] },
  { id: 'reports', label: 'Reports', group: 'SYSTEM', icon: '▤', description: 'Operational, financial and custom reporting', ai: true, capabilities: ['sales', 'orders', 'inventory', 'products', 'listings', 'returns', 'finance', 'advertising', 'profit', 'marketplace', 'tax', 'custom', 'scheduled', 'PDF', 'Excel', 'CSV'] },
  { id: 'settings', label: 'Settings', group: 'SYSTEM', icon: '⚙', description: 'Business, marketplace and Seller OS configuration', ai: false, capabilities: ['business profile', 'seller profile', 'marketplace accounts', 'warehouse', 'GST', 'shipping', 'notifications', 'AI settings', 'automation settings', 'appearance', 'data management', 'backup', 'system preferences'] },
];

export const sellerHubGlobalUX = ['global search', 'AI search', 'command palette', 'date range', 'marketplace filter', 'warehouse filter', 'SKU filter', 'advanced filters', 'saved filters', 'export', 'refresh', 'bulk select/actions', 'pagination', 'sorting', 'column customization', 'detail drawer', 'confirmation modal', 'toasts', 'loading skeleton', 'empty state', 'error state', 'retry', 'keyboard shortcuts', 'dark mode', 'responsive layout', 'activity timeline', 'audit trail', 'contextual AI'];
